version: "3.9"

services:
  api:
    build:
      context: ./apps/api
    container_name: foodhub-api
    ports:
      - "5000:5000"
    env_file:
      - ./apps/api/.env
    restart: unless-stopped

  web:
    build:
      context: ./apps/web
    container_name: foodhub-web
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - api